### ISSUE TITLE
BNB methods

### ISSUE THREAD

**Issue by maxxx** [centerprime/BinanceSmartChain-Android-SDK#2]
Hi! BinanceManager has method "sendBNB", but the code and comment looks like it's about sending Ether -
https://github.com/centerprime/BinanceSmartChain-Android-SDK/blob/eb5fc642e3491c9fa6ab8911da11df0399d420b7/binance-smart-chain-sdk/src/main/java/com/centerprime/binance_smart_chain_sdk/BinanceManager.java#L350

so is it really for send BNB? Tried sending with 'sendToken' and  contract address 0xB8c77482e45F1F44dE1745F52C74426C631bDD52 - contract is empty 

edit: same for getBNBBalance, it works as BNB but comments and code about Ether

**Comment by centerprime** [comment]
Hi! To send a BNB, you must first import your wallet using the importFromKeystore or importFromPrivateKey functions. By the way, the comments have been corrected. Feel free to reopen the issue, if you still need help. 👍
